version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
  - dependency-name: pdfkit
    versions:
    - 0.11.0
    - 0.12.0
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: opusscript
    versions:
    - 0.0.7
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: node-ipc
    versions:
    - 9.1.3
